// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
 // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Basics',
      items: [
          {
          type: 'doc',
          id: 'basics/start', // Path relative to the 'docs' folder
          label: 'Getting Started', // Custom label for 'start.md'
        },       // start.md
         'basics/nodes',    
          'basics/designer',       // designer.md   
       // 'basics/layout',         // layout.md
        'basics/customElements', // customElements.md
      //  'basics/animation',      // animation.md
      //  'basics/transitions',    // transitions.md
       
       
       // 'basics/encrypt',        // encrypt.md
      //  'basics/integration',    // integration.md
       // 'basics/my',             // my.md
          // nodes.md
        
      //  'basics/template',       // template.md
       // 'basics/using-vue',      // using-vue.md
      ],
    },

    {
      type: 'category',
      label: 'Nodes',
      items: [
        'nodes/animation',       // animation.md
        'nodes/filter',          // filter.md
        'nodes/layout',          // layout.md
        'nodes/blast',           // blast.md
        'nodes/gradient',        // gradient.md
        'nodes/linkStyle',       // linkStyle.md
        'nodes/span',            // span.md
        'nodes/transform',       // transform.md
      ],
    },


    {
      type: 'category',
      label: 'Elements',
      items: [
        'elements/cards',                   // cards.md
        'elements/keyset',                  // keyset.md
        'elements/row',                     // row.md
        'elements/code',                    // code.md
        'elements/link',                    // link.md
        'elements/sidenavigation',          // sidenavigation.md
        'elements/dropdown',                // dropdown.md
        'elements/slider',                  // slider.md
        'elements/free',                    // free.md
        'elements/modal',                   // modal.md
        'elements/stack',                   // stack.md
        'elements/grid',                    // grid.md
        'elements/navigation',              // navigation.md
        'elements/offcanvas',               // offcanvas.md
        'elements/responsive-wrapper',      // responsive-wrapper.md
        'elements/switcher',                // switcher.md
        'elements/table',                   // table.md
        'elements/text',                    // text.md
        'elements/weightLayout',            // weightLayout.md
        'elements/wrap',                    // wrap.md
        'elements/zoom-card',               // zoom-card.md
      ],
    },


      {
      type: 'category',
      label: 'Forms',
      items: [
        'forms/button',          // button.md
        'forms/filepicker',      // filepicker.md
        'forms/picker',          // picker.md
        'forms/checkbox',        // checkbox.md
        'forms/labelfield',      // labelfield.md
        'forms/radio',           // radio.md
        'forms/textfield',       // textfield.md
        'forms/together',        // together.md
        'forms/usewithphp',      // usewithphp.md
      ],
    },
    

    {
      type: 'category',
      label: 'Scroll Animation',
      items: [
        'scrollanimation/basics',              // basics.md
        'scrollanimation/scrollvideo',         // scrollvideo.md
        'scrollanimation/transformanimation',  // transformanimation.md
        'scrollanimation/together',            // together.md
      ],
    },
     {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/integration',     // integration.md
        'guides/transitions',     // transitions.md
        'guides/testing',     // testing.md
      ],
    },
  ],
};

export default sidebars;
